[workspace]
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
name = "simple_cart_pole"
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
train = "python cart_pole_env.py"

[dependencies]
gz-math = "*"
gz-sim = "10.*"
gymnasium = "*"
py-opencv = "*"
numpy = "*"
stable-baselines3 = "*"
